//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KICHCOSP
    {
        public string MaKichCo { get; set; }
        public string KichCo { get; set; }
        public int SoLuong { get; set; }
        public string MaSP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
